### PR TITLE
Darkmode edits

### PR DESCRIPTION
**Pull request by Scrxtchy**
These are some old edits I did, but I feel that it is neccessary again to update for vs2019
Extension Gallery version looks outdated, getting this in there before an update would prevent further effort

image

Putting this as a draft until I can review anything for 2019 version

### CODE REVIEW

**Comment by Scrxtchy** [comment]
Updating list of notes:
- [x] Live Share Button on hover
image
- [x] This tile can be changed
image
- [ ] These should be dark
image
- [x] Live share/feedback button use light mode glyphs
image
<del>Hover Transparency of blocks (Text Editor -> Collapsible Region ?)</del> Does not support alpha
image

**Comment by Scrxtchy** [comment]
Also, a diff
https://gist.github.com/Scrxtchy/3787a9e92665f0e231d10707963feb51

**Comment by huoyaoyuan** [comment]
The color theme format of VS is not program-friendly editable, and vs color theme editor is very complex. So I don't want to edit it manually any more.
Thank you for editing this.

**Comment by Scrxtchy** [comment]
> The color theme format of VS is not program-friendly editable

Yeah it's a bit rough, the colour themes extension allows exporting an XML, which really really helps
It would help if we had the colour theme these were initially based off, as then I could probably do a better job in just applying those changes into the updated colours, instead of going through every change and seeing what's important

**Comment by Scrxtchy** [comment]
Found a good diff tool, really helps in finding the transparent values
image

**Comment by Scrxtchy** [comment]
I've completed a decent effort, there's still quite a bit of minor changes to colours over the years, but this appears to function as intended.

some xml files are stored in this gist file, as I try to remember how I pulled out theme configs from six months ago to commit them into the repo
https://gist.github.com/Scrxtchy/d450ca7aee33b3a7ca3ddb091c39938e

does appear to be some things I missed though 🙄

**Comment by huoyaoyuan** [comment]
What I ultimately want is generating a complete table with just master hue and transparency.
The easiest way should be joining VS dev team and expose their potential internal tools.

**Pull request merged**
